export const GET_TASKS_REQUEST = 'GETTING_TASKS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';


export const DELETE_BULK_REQUEST = 'DELETE_BULK_REQUEST';
export const DELETE_BULK_SUCCESS = 'DELETE_BULK_SUCCESS';
export const DELETE_BULK_FAILURE = 'DELETE_BULK_FAILURE';

export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE';


export const SINGLETASK_REQUEST='SINGLETASK_REQUES';
export const SINGLETASK_SUCCESS='SINGLETASK_SUCCESS';
export const SINGLETASK_FAILURE='SINGLETASK_FAILURE';